name: CI

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch:

jobs:
  package:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Print Gradle version
        run: ./gradlew --version

      - name: Build debug APK
        run: ./gradlew assembleDebug --info --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: pratik_poc_debug_apk
          path: app/build/outputs/apk/debug/app-debug.apk


